name: Users MS CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  ci:
    uses: Projet-technique-Altair/altair-ci/.github/workflows/rust-ms.yml@v1
    with:
      rust_toolchain: stable